Class {
	#name : 'LayerNeuralNetworkMachineLearningRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-NeuralNetwork-Private',
	#package : 'Rudesheim-NeuralNetwork-Private'
}

{ #category : 'as yet unclassified' }
LayerNeuralNetworkMachineLearningRudesheim class >> Add [
	^ AddLayerNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerNeuralNetworkMachineLearningRudesheim class >> BatchNormalization [
	^ BatchNormalizationLayerNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerNeuralNetworkMachineLearningRudesheim class >> Conv2D [
	^ Conv2DLayerNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerNeuralNetworkMachineLearningRudesheim class >> GlobalAveragePool [
	^ GlobalAveragePoolLayerNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerNeuralNetworkMachineLearningRudesheim class >> LinearTransform [
	^ LinearTransformLayerNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerNeuralNetworkMachineLearningRudesheim class >> MaxPool2D [
	^ MaxPool2DLayerNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerNeuralNetworkMachineLearningRudesheim class >> ReLU [
	^ ReLULayerNeuralNetworkMachineLearningRudesheim.
]
