Class {
	#name : 'NeuralNetworkMachineLearningRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-NeuralNetwork-Private',
	#package : 'Rudesheim-NeuralNetwork-Private'
}

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Architecture [

	^ ArchitectureNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> BackwardContext [

	^ BackwardContextNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Criterion [

	^ CriterionNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Layer [

	^ LayerNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Model [

	^ ModelNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> ONNX [

	^ ONNXNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Node [

	^ NodeNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> OpenCL [

	^ OpenCLNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Predictions [

	^ PredictionsNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Pure [

	^ PureNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Soil [

	^ SoilNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Trace [

	^ TraceNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> Trainer [

	^ TrainerNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
NeuralNetworkMachineLearningRudesheim class >> WeightsSource [

	^ WeightsSourceNeuralNetworkMachineLearningRudesheim
]
