Class {
	#name : 'PureNeuralNetworkMachineLearningRudesheim',
	#superclass : 'Object',
	#traits : 'TBackendNeuralNetworkMachineLearningRudesheim',
	#classTraits : 'TBackendNeuralNetworkMachineLearningRudesheim classTrait',
	#category : 'Rudesheim-NeuralNetwork-Private',
	#package : 'Rudesheim-NeuralNetwork-Private'
}

{ #category : 'namespace' }
PureNeuralNetworkMachineLearningRudesheim class >> Criterion [

	^ CriterionNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
PureNeuralNetworkMachineLearningRudesheim class >> Layer [

	^ LayerNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
PureNeuralNetworkMachineLearningRudesheim class >> Model [

	^ ModelNeuralNetworkMachineLearningRudesheim
]
