Trait {
	#name : 'TActivationLayerNeuralNetworkMachineLearningRudesheim',
	#traits : 'TLayerNeuralNetworkMachineLearningRudesheim',
	#classTraits : 'TLayerNeuralNetworkMachineLearningRudesheim classTrait',
	#category : 'Rudesheim-NeuralNetwork-Private',
	#package : 'Rudesheim-NeuralNetwork-Private'
}

{ #category : 'converting' }
TActivationLayerNeuralNetworkMachineLearningRudesheim classSide >> withUpdatedWeightsRows:	aTLinearTransformLayerNeuralNetworkMachineLearningRudesheim
learningRate:				aRateFloat [
				
	^ self.
]
