"
TensorSoilNeuralNetworkMachineLearningRudesheim is the namespace for internal tensor role classes stored in Soil tensor descriptors.
"
Class {
	#name : 'TensorSoilNeuralNetworkMachineLearningRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-NeuralNetwork-Private',
	#package : 'Rudesheim-NeuralNetwork-Private'
}

{ #category : 'namespace' }
TensorSoilNeuralNetworkMachineLearningRudesheim class >> Biases [

	^ BiasesTensorSoilNeuralNetworkMachineLearningRudesheim
]

{ #category : 'namespace' }
TensorSoilNeuralNetworkMachineLearningRudesheim class >> Weights [

	^ WeightsTensorSoilNeuralNetworkMachineLearningRudesheim
]
