Trait {
	#name : 'TModelSourceNeuralNetworkMachineLearningRudesheim',
	#traits : 'TModelReaderNeuralNetworkMachineLearningRudesheim + TModelWriterNeuralNetworkMachineLearningRudesheim',
	#classTraits : 'TModelReaderNeuralNetworkMachineLearningRudesheim classTrait + TModelWriterNeuralNetworkMachineLearningRudesheim classTrait',
	#category : 'Rudesheim-NeuralNetwork-Private-IO',
	#package : 'Rudesheim-NeuralNetwork-Private',
	#tag : 'IO'
}
