Trait {
	#name : 'TModelReaderNeuralNetworkMachineLearningRudesheim',
	#category : 'Rudesheim-NeuralNetwork-Private',
	#package : 'Rudesheim-NeuralNetwork-Private'
}

{ #category : 'reading' }
TModelReaderNeuralNetworkMachineLearningRudesheim classSide >> nextModelAs: aClass [

	^ self subclassResponsibility
]

{ #category : 'reading' }
TModelReaderNeuralNetworkMachineLearningRudesheim >> nextModelAs: aClass [

	^ self subclassResponsibility
]
