Trait {
	#name : 'TWeightsSourceNeuralNetworkMachineLearningRudesheim',
	#category : 'Rudesheim-NeuralNetwork-Private',
	#package : 'Rudesheim-NeuralNetwork-Private'
}

{ #category : 'accessing' }
TWeightsSourceNeuralNetworkMachineLearningRudesheim >> biases [

	^ self subclassResponsibility
]

{ #category : 'accessing' }
TWeightsSourceNeuralNetworkMachineLearningRudesheim >> weightsRows [

	^ self subclassResponsibility
]
