Class {
	#name : 'LayerOpenCLNeuralNetworkMachineLearningRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-NeuralNetwork-OpenCL-Private',
	#package : 'Rudesheim-NeuralNetwork-OpenCL-Private'
}

{ #category : 'as yet unclassified' }
LayerOpenCLNeuralNetworkMachineLearningRudesheim class >> Add [
	^ AddLayerOpenCLNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerOpenCLNeuralNetworkMachineLearningRudesheim class >> BatchNormalization [
	^ BatchNormalizationLayerOpenCLNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerOpenCLNeuralNetworkMachineLearningRudesheim class >> Conv2D [
	^ Conv2DLayerOpenCLNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerOpenCLNeuralNetworkMachineLearningRudesheim class >> GlobalAveragePool [
	^ GlobalAveragePoolLayerOpenCLNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerOpenCLNeuralNetworkMachineLearningRudesheim class >> LinearTransform [
	^ LinearTransformLayerOpenCLNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerOpenCLNeuralNetworkMachineLearningRudesheim class >> MaxPool2D [
	^ MaxPool2DLayerOpenCLNeuralNetworkMachineLearningRudesheim.
]

{ #category : 'as yet unclassified' }
LayerOpenCLNeuralNetworkMachineLearningRudesheim class >> ReLU [
	^ ReLULayerOpenCLNeuralNetworkMachineLearningRudesheim.
]
